#!/bin/sh

VAR_PATH="/app.reg/dict/"

NAME=$1

if [ "${2:0:1}" = "-" ] ; then
    ACTION=$2

    if [ "${3:0:1}" = "-" ] ; then
        OPTION=$3
        KEY=$4
        VALUE=$5
    else
        OPTION=""
        KEY=$3
        VALUE=$4
    fi
elif [ -z "$3" ] ; then
    ACTION="-g"
    KEY=$2
else
    ACTION="-s"
    KEY=$2
    VALUE=$3
fi

mkdir -p $VAR_PATH

case $ACTION in

    "-d") # delete (dict)
        rm -f $VAR_PATH$NAME >/dev/null
    ;;
    "-r") # remove (key)
        sed -i "/^$KEY:.*$/d" $VAR_PATH$NAME
    ;;
    "-a") # append
        sed -i "s/^$KEY:\(.*\)$/$KEY:\1 $VALUE/g" $VAR_PATH$NAME
    ;;
    "-g") # get
        cat $VAR_PATH$NAME 2>/dev/null | grep "$KEY:" | sed 's/^.*:\(.*\)$/\1/g'
    ;;
    "-s") # set
        if [ "$(cat $VAR_PATH$NAME 2>/dev/null | grep "^$KEY:")" ] ; then
            sed -i "/^$KEY:.*$/d" $VAR_PATH$NAME
        fi

        echo "$KEY:$VALUE" >> $VAR_PATH$NAME
    ;;
    "-e") # exists
        test -f $VAR_PATH$NAME
        echo $?
    ;;

esac
