#!/bin/sh

# Get current application
app=$(ps | grep "^\s*$PPID " | sed -n 's/.*\/app\/\([^\/]*\)\/.*/\1/p')
if [ -z "$app" ]
then
    app="supervisor"
fi

# Get message and level
while getopts ":v:d:i:w:e:" arg
do
    case $arg in
        *) clevel=$arg; msg="$OPTARG";;
    esac

    # Translate message level
    case $clevel in
        v) level=1; label="VER";;
        d) level=2; label="DBG";;
        i) level=3; label="INF";;
        w) level=4; label="WAR";;
        e) level=5; label="ERR";;
    esac

    # Translate selected log level
    case $(var LOG_LEVEL) in
        v|ver|verbose) threshold=0;;
        d|deb|debug) threshold=1;;
        i|inf|info|information) threshold=2;;
        w|war|wrn|warning) threshold=3;;
        e|err|error) threshold=4;;
        *) threshold=2;;
    esac

    # Backwards compability
    if [ $# -eq 3 ]
    then
        msg="$3"
    fi

    # Log
    if [ $level -gt $threshold ]
    then
        timestamp=$(date +"%Y-%m-%d %T")
        printf "[$timestamp $label] [%-10s] $msg\n" "${app:0:10}" >> /var/log/main.log
    fi

    # Backwards compability
    if [ $# -eq 3 ]
    then
        break;
    fi

done

exit 0;
