#!/bin/sh

case $1 in
    "-v") LEVEL=1; LABEL="VER";;
    "-d") LEVEL=2; LABEL="DBG";;
    "-i") LEVEL=3; LABEL="INF";;
    "-w") LEVEL=4; LABEL="WAR";;
    "-e") LEVEL=5; LABEL="ERR";;
    *) LEVEL=3; LABEL="INF";;
esac

case $LOG_LEVEL in
    "verbose") THRESHOLD=0;;
    "debug") THRESHOLD=1;;
    "info") THRESHOLD=2;;
    "warning") THRESHOLD=3;;
    "error") THRESHOLD=4;;
    *) THRESHOLD=2;;
esac


if [ $LEVEL -gt $THRESHOLD ] ; then
    echo "[$LABEL] $2" >> /var/log/main.log
fi
