#!/bin/sh

mkdir -p /app.reg/var/

if [ "$1" = "-i" ] ; then
    printenv | while read line; do
        var=$(echo "$line" | sed 's/\(.*\)=\(.*\)$/\1/g')
        val=$(echo "$line" | sed 's/\(.*\)=\(.*\)$/\2/g')
        echo "$val" > /app.reg/var/$var
    done

    exit 0;
fi

NAME=$1
VALUE=$2

echo $VALUE > /app.reg/var/$NAME
