#!/bin/sh

if [ "$1" = "-i" ] ; then
    for var in $(env) ; do
        $(echo $var | sed 's/\(.*\)=\(.*\)$/setv \1 \2/g')
    done

    exit 0;
fi

NAME=$1
VALUE=$2

mkdir -p /app.reg/var/

echo "$2" > /app.reg/var/$1